### ISSUE TITLE
Personal site under Contact doesn't have anything

### ISSUE THREAD

**Issue by dawidpotocki** [MrCyjaneK/mrcyjanek.net#7]
> Congratulations, the site was created successfully!
> The site was created successfully and this page is automatically generated by the system.
> This page is index.html in the FTP root directory.
> You can delete or overwrite this page
> For FTP related information, please check the background of the pagoda.
> We provide you with a comprehensive data backup function, please go to the background to set up

**Comment by MrCyjaneK** [comment]
[this is](https://contact.mrcyjanek.net/) already fixed.
