### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by dawidpotocki** [MrCyjaneK/mrcyjanek.net#8]
For now nobody can do anything with it, which makes it on GitHub really useless.
https://choosealicense.com/no-permission/

I would suggest something like [ISC License](https://choosealicense.com/licenses/isc/).

**Comment by MrCyjaneK** [comment]
I think that I've chosen [perfect solution](https://github.com/MrCyjaneK/mrcyjanek.net/blob/master/LICENSE) for this
